application:
  property4: "Staging environment specific value"
  property5: "Staging environment specific value"

aws:
  s3:
    bucket: "stage-bucket"
  firehose:
    deliveryStream: "stage-deliverystream"

