application:
  property4: "Development environment specific value"
  property5: "Development environment specific value"

aws:
  s3:
    bucket: "dev-bucket"
  firehose:
    deliveryStream: "dev-deliverystream"

